version: '3'

services:
  backend:
    build: ./backend
    container_name: flask-api
    ports:
      - "8090:80"
    volumes:
      - ./backend/data:/app/data  # Carpeta local "backend/data" mapeada dentro del contenedor

  preguntados:
    image: nginx
    container_name: preguntados
    volumes:
      - ./preguntados:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8070:80"

